# Generated by Django 4.2.11 on 2024-04-03 15:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_usedtechnology_alter_homepage_options_homepage_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usedtechnology",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usedtechnology", unique_together={("color", "name")},
        ),
    ]
